#define UBB_VS_VIEW_PARAMS	0
#define UBB_VS_DRAW_PARAMS	1
#define UBB_FS_VIEW_PARAMS	2
#define UBB_FS_DRAW_PARAMS	3
#define UBB_LIGHT_DATA      4
#define UBB_COMMON_DATA     5
#define UBB_SHARED_DATA     6

#define	IMU_DIFFUSE 0
#define	IMU_NORMAL 1
#define IMU_AORM 2
#define IMU_EMISSIVE 3
#define IMU_DEPTH 4
#define IMU_FRAGPOS 5
#define IMU_HDR 6
#define IMU_SHADOW 7
#define IMU_DEFAULT 8

#define SSAO_KERNEL_SAMPLES 12
